### ISSUE TITLE
Add claimDate

### ISSUE THREAD

**Issue by janndriessen** [Developer-DAO/code-claim-site#48]
When the user has claimed it should show the `claimDate`.

(Currently this is just the current day's date.)

Wait for #45 to be merged before doing this issue.

**Comment by SouravInsights** [comment]
Is anyone working on this or I can take this up? @janndriessen & @helloitsm3

**Comment by SouravInsights** [comment]
Cool. Let's set some context here @janndriessen & @helloitsm3:

So I think this is [state value](https://github.com/Developer-DAO/code-claim-site/blob/main/packages/next-app/src/components/ClaimCard.tsx#L139) we are dealing with.

And if I'm not wrong, the functionality for fetching the claim date is yet to be implemented using ethers.js?

**Comment by helloitsm3** [comment]
> Cool. Let's set some context here @janndriessen & @helloitsm3:
> 
> So I think this is [state value](https://github.com/Developer-DAO/code-claim-site/blob/main/packages/next-app/src/components/ClaimCard.tsx#L139) we are dealing with.
> 
> And if I'm not wrong, the functionality for fetching the claim date is yet to be implemented using ethers.js, right?

Yes correct

**Comment by embiem** [comment]
Hey, sorry for jumping in but this is now fixed in the preview branch, which I'll merge back into main at some point.

If you're interested, this is how I've implemented it: https://github.com/Developer-DAO/code-claim-site/pull/60/files#diff-1503defb5654bb80065579ddbf8ee14282b0e7400a2d3b91065acc344d4dae19R148-R160
